### ISSUE TITLE
TOC that mixes drop-downs with individual files?

### ISSUE THREAD

**Issue by rgiordan** [berkeley-scf/stat999-myst#9]
Is there a way in Myst to mix "parts" and files in the table of contents?  For example, I would like the TOC to contain a link "Syllabus" directly to "syllabus.md," and then an expandable box called "Lectures" with links to a bunch of individual lecture markdown files.

For example, you might hope that this would work, but the Lectures section just doesn't show up:

```
chapters:
- file: syllabus
parts:
  - caption: Lectures
    chapters:
    - file: Lectures/Lecture1.md
    - file: Lectures/Lecture2.md
```
